### ISSUE TITLE
Object not working

### ISSUE THREAD

**Issue by Pepn** [aviate-labs/json.mo#4]
## Expected Behavior
working example code

## Actual Behavior
`var obj : JSON.JSON = #Object([]);`

gives error:
```
type error [M0096], expression of type
  [None]
cannot produce expected type
  {
    delete : Text -> ();
    entries : () -> Iter__1<(Text, JSON)>;
    get : Text -> ?JSON;
    keys : () -> Iter__1<Text>;
    put : (Text, JSON) -> ();
    remove : Text -> ?JSON;
    replace : (Text, JSON) -> ?JSON;
    size : () -> Nat;
    vals : () -> Iter__1<JSON>
  }
```

## Steps to Reproduce the Problem
imported the vessel package

## Specifications
`Debug.print(JSON.show(#String("hello")));`
Does work.

- Version(s):
let upstream = https://github.com/dfinity/vessel-package-set/releases/download/mo-0.7.3-20221102/package-set.dhall sha256:9c989bdc496cf03b7d2b976d5bf547cfc6125f8d9bb2ed784815191bd518a7b9
let aviate-labs = https://github.com/aviate-labs/package-set/releases/download/v0.1.7/package-set.dhall sha256:433429e918c292301ae0a7fa2341d463fea2d586c3f9d03209d68ca52e987aa8
dfx 0.11.2

**Comment by q-uint** [comment]
Make sure you have the latest versions installed. It seems like `#Object` still expects the old `HashMap` instead of an array.
